= ADR 4: Use JUnit 5 Test Platform

== Context

To achieve great usability, LivingDoc needs good integration with the ecosystem
of the dominant JVM platform. Documents have to be executed in different
contexts:

- the domain expert changes a spec and wants to execute it;
- the developer writes and tests fixture code;
- the CD pipeline validates a release candidate.

[...]
In LivingDoc Legacy we had multiple plugins which provided execution of documents
for different contexts:

- from an IDE (e.g. Eclipse, IntelliJ)
- by a standalone build tool (e.g. Maven, Gradle)

Providing this support requires that we build and maintain integrations for
these tools.
[to decision] Having just one way of executing documents,
which works for all of these contexts, would save us a lot of maintenance work.

With the development of JUnit 5 there is a way of implementing generic _test engines_
which are used by the _JUnit Platform_ to execute all kinds of custom tests. The
platform is integrated in all of the popular IDEs and build tools.


== Decision

We will implement a JUnit 5 test engine.

We will implement a JUnit 5 _test engine_ for the execution of LivingDoc documents.
This test engine will be the bridge between the _JUnit Platform_ and LivingDoc.


== Status

Proposed.


== Consequences

* We'll have to maintain only one integration module.
* We don't need to handle the integration into IDEs or build tools
[nope:] * We won't provide UIs for the IDEs like we did in LivingDoc Legacy
* Supporting languages on non-JVM platforms will require more work

